CREATE DATABASE DB_TRIGGER

USE DB_TRIGGER

create table Reservation1 
( 
Aircraft_Code varchar(10), 
No_of_Seats int, 
Class_Code varchar(10) 
)

create table Reservation2 
( 
Aircraft_Code varchar(10), 
No_of_Seats int, 
Class_Code varchar(10) 
)

-- REQUIREMENT	:	WHENEVER WE INSERT DATA INTO 1ST TABLE, IT SHOULD AUTO INSERT DATA INTO 2ND TABLE.
CREATE TRIGGER trigAdditionalOperation
ON Reservation1
FOR			-- IN ADDITION TO
INSERT
AS 
INSERT INTO Reservation2 SELECT * FROM INSERTED 


-- TO TEST ABOVE TRIGGER:
SELECT * FROM Reservation1
SELECT * FROM Reservation2 

INSERT INTO Reservation1 VALUES ('EMI1', 11, 'ECO')			-- trigger is auto executed. 
INSERT INTO Reservation1 VALUES ('EMI2', 22, 'ECO')			-- trigger is auto executed. 

SELECT * FROM Reservation1
SELECT * FROM Reservation2 


-- REQ 2: RESERVATIONS ONCE CONFIRMED (INSERTED) CANNOT BE MODIFIED (UPDATE) OR CANCELLED (DELETE).
-- MEANS, HOW TO MAKE A TABLE AS "READ ONLY"?
CREATE TRIGGER trigPreventOps 
ON Reservation1
INSTEAD OF						-- INSTEAD OF  :  IN PLACE OF 
INSERT, UPDATE, DELETE
AS
	PRINT 'RESERVATIONS ONCE APPROVED CANNOT BE MODIFIFED OR CANCELLED. CONTACT YOUR ADMIN.'


DELETE FROM Reservation1				-- actual delete will not happen. Trigger prevents the DELETE event.
select * from Reservation1

DISABLE TRIGGER trigPreventOps ON Reservation1	-- TO DISABLE A TRIGGER. ONLY DATABASE ADMINS CAN PERFORM THIS OPERATION
DELETE FROM Reservation1						-- DELETE IS SUCESSFUL	
select * from Reservation1

ENABLE TRIGGER trigPreventOps ON Reservation1	-- TO ENABLE A TRIGGER. ONLY DATABASE ADMINS CAN PERFORM THIS OPERATION
DELETE FROM Reservation1						-- WE CANNOT DELETE THE TABLE DATA	


-- TO AUDIT THE TRIGGERS IN A DATABASE:
SELECT * FROM SYS.TRIGGERS 

DROP TRIGGER trigPreventOps


-- TASK 1	:	YOU WERE GIVEN TWO DATABASES. TWO SIMILAR TABLES EXIST IN THESE TWO DATABASES.
				WHENEVER YOU INSERT DATA INTO 1ST TABLE IT SHOULD AUTO REPLICATE SAME DATA INTO 2ND TABLE

-- TASK 2	:	HOW CAN YOU PROOVE THAT INSTEAD OF TRIGGER HAS MORE PRIORITY THAN FOR TRIGGER? EXAMPLE.


